### ISSUE TITLE
Timezone error

### ISSUE THREAD

**Issue by mote166** [SuperKali/CustomBar#10]
I get this when i start the server and join it:

Notice: date_default_timezone_set(): Timezone ID 'UTC+3' is invalid in /storage/emulated/legacy/Genisys/plugins/CustomBar-master/src/CustomBar/Main.php on line 43

*UTC+3 is my timezone i think , my country is KSA (kingdom saudi arabia) .

**Comment by TheNewHEROBRINEX** [comment]
Try Asia/Riyadh as timezone

**Comment by SuperKali** [comment]
@mote166 try AST

**Comment by mote166** [comment]
Same error and the time isn't changing

**Comment by SuperKali** [comment]
Please send me your config

**Comment by mote166** [comment]
AST didn't work but Asia/Riyadh worked , thanks

**Comment by mote166** [comment]
Can u add "AM , PM" and make the time 12 hour format ?

**Comment by SuperKali** [comment]
Ok on to-do v1

**Comment by mote166** [comment]
Please do it fast it won't take much of ur time , thanks for this great plugin 👍

**Comment by SuperKali** [comment]
😊

**Comment by SuperKali** [comment]
@mote166 https://github.com/SuperKali/CustomBar/commit/90526ce3660d3ead59662e964190d138d976b593
time format added
