### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by naja82** [SuperKali/CustomBar#14]
## Issue description
Suggestion

## Client information
PocketMine-MP Version: PocketMine-MP API 3.0.0-dev-1001 ALPHA12
MCBE Version: MC Bedrock 1.4.1
Plugin Version: 0.9
PHP version: PHP 7.2 (MCC++  2017) Windows (ZTS)
## Optional information
Please add Item ID, Client IP, Server IP
You can look at SuperBar by FaigerSYS

**Comment by naja82** [comment]
Also add Server Uptime if its possible

**Comment by SuperKali** [comment]
@naja82 already avaiable

**Comment by naja82** [comment]
I did not see item id

**Comment by SuperKali** [comment]
Send me error
